# Dependencies
gems:             [jekyll-paginate, jekyll-gist]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
encoding:         UTF-8 
excerpt_separator: <!--more-->
title:            fmendo
tagline:          'fmendo.com'
description:      'Hi, I&#8217;m Filipe and I&#8217;m a Windows Developer living in London'
url:              http://www.fmendo.com
baseurl:          /

author:
  name:           'Filipe Duarte'
  url:            https://twitter.com/fmmendo

paginate:         8

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fmmendo/fmmendo.github.io
