title:            fmendo
description:      'Hi, I&#8217;m Filipe and I&#8217;m a Software Engineer living in London'

# put your disqus here
disqus_shortname: fmendo
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://www.fmendo.com

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'blog'
    url: '/'
  - title: 'projects'
    url: '/projects'
  - title: 'about'
    url: '/about'
  - title: 'more...'
    url: '#'
    submenu:
      - title: 'travel'
        url: '/travel'
      - title: 'tags'
        url: '/tags'
      - title: 'archive'
        url: '/posts'
      - title: 'rss'
        url: '/feed.xml'

# Owner/author information
owner:
  name:           Filipe Duarte
  site:           http://www.fmendo.com
  avatar:         images/avatar.jpg
  bio:            "Hi, I&#8217;m Filipe. I&#8217;m a Software Engineer, from Portugal, currently living in London, building stuff for Paddle."
  email:          me@fmendo.com
  # Twitter nick for use in Twitter cards and follow button.
  # twitter: fmmendo # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  # github: fmmendo

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/fmmendo"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/filipemiguel"
  - title: "twitter"
    url: "https://www.twitter.com/fmmendo"
  - title: "instagram"
    url: "https://www.instagram.com/fmmendo"
  - title: "envelope"
    url: "mailto:me@fmendo.com"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
locale:      en_GB
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /blog/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
