# Dependencies
gems: [jekyll-paginate, jekyll-feed]
markdown:         kramdown
highlighter:      rouge

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Permalinks
permalink:        pretty

# Setup
encoding:         UTF-8 
excerpt_separator: <!--more-->

title:            fmendo
tagline:          'fmendo.com'
description:      'Hi, I&#8217;m Filipe and I&#8217;m a Windows Developer living in London'
header-img: img/about-bg.jpg
url:              http://www.fmendo.com
baseurl:          http://www.fmendo.com/
root:             /

email: me@fmendo.com
copyright_name: Filipe Duarte

author:
  name:           'Filipe Duarte'
  url:            https://twitter.com/fmmendo

paginate:         8

# Custom vars
version:          2.1.0

twitter_username: fmmendo
github_username: fmmendo
linkedin_username: filipemiguel
instagram_username: fmmendo
facebook_username: fmmendo
email_username:  me@fmendo.com


github:
  repo:           https://github.com/fmmendo/fmmendo.github.io
