# Dependencies
gems:             [jekyll-paginate, jekyll-gist]
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            fmendo
tagline:          'fmendo.com'
description:      'What should, I hope, become by website by the end of the week.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Filipe Duarte'
  url:            https://twitter.com/fmmendo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fmmendo/fmmendo.github.io
