name: Publish Drafts

on:
  workflow_dispatch:
    #- cron: "10/60 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Jekyll Publish Drafts
        uses: soywiz/github-action-jekyll-publish-drafts@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_path: ./
          branch: main
